var express = require('express'),
    router = express.Router(),
    indexRouter = require('../controllers/index');
// usersRouter = require('./controllers/users');
aboutRouter = require('../controllers/about');
contactRouter = require('../controllers/contact');
userSigninRouter = require('../controllers/user_signin');
updateAccountRouter = require('../controllers/update_account');
signoutRouter = require('../controllers/signout');
signupRouter = require('../controllers/signup');
registerRouter = require('../controllers/register');
gymRouter = require('../controllers/gym');
aeroRouter = require('../controllers/aero');
yogaRouter = require('../controllers/yoga');
faqRouter = require('../controllers/faq');
adminSignupRouter = require('../controllers/admin_signup');
adminRouter = require('../controllers/admin');
adminDetailsRouter = require('../controllers/admin_details');
adminSignOutRouter = require('../controllers/admin_signout');
adminSignupDetailsRouter = require('../controllers/admin_signup_details');
adminRegisterDetailsRouter = require('../controllers/admin_resgistration_details');
trainerDetailsRouter = require('../controllers/trainer_details');
getTrainerRouter = require('../controllers/get_trainer');
trainerUpdateRouter = require('../controllers/trainer_update');
removeTrainerRouter = require('../controllers/remove_trainer');
addFAQRouter = require('../controllers/add_faq');
getFAQRouter = require('../controllers/get_faq');
upadateFAQRouter = require('../controllers/update_faq');
removeFAQRouter = require('../controllers/remove_faq');
// headerRouter = require('../controllers/header');
testRouter = require('../controllers/test');

router.use('/', indexRouter);
// app.use('/users', indexRouter);
router.use('/about', aboutRouter);
router.use('/contact', contactRouter);
router.use('/usersignin', userSigninRouter);
router.use('/userupdate', updateAccountRouter);
router.use('/signout', signoutRouter);
router.use('/signup', signupRouter);
router.use('/registration', registerRouter);
router.use('/gym', gymRouter);
router.use('/aerobics', aeroRouter);
router.use('/yoga', yogaRouter);
router.use('/faq', faqRouter);
router.use('/adminsignup', adminSignupRouter);
router.use('/admin', adminRouter);
router.use('/admindetails', adminDetailsRouter);
router.use('/adminsignout', adminSignOutRouter);
router.use('/adminsignupdetails', adminSignupDetailsRouter);
router.use('/adminregistrationdetails', adminRegisterDetailsRouter);
router.use('/trainerdetails', trainerDetailsRouter);
router.use('/gettrainer', getTrainerRouter);
router.use('/trainerupdate', trainerUpdateRouter);
router.use('/removetrainer', removeTrainerRouter);
router.use('/addfaq', addFAQRouter);
router.use('/getfaq', getFAQRouter);
router.use('/upadatefaq', upadateFAQRouter);
router.use('/removefaq', removeFAQRouter);
// router.use('/header', headerRouter);
router.use('/test', testRouter);

module.exports = router;